// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralDescription) DeepCopyInto(out *GeneralDescription) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralDescription.
func (in *GeneralDescription) DeepCopy() *GeneralDescription {
	if in == nil {
		return nil
	}
	out := new(GeneralDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mosaic5g) DeepCopyInto(out *Mosaic5g) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mosaic5g.
func (in *Mosaic5g) DeepCopy() *Mosaic5g {
	if in == nil {
		return nil
	}
	out := new(Mosaic5g)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mosaic5g) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mosaic5gList) DeepCopyInto(out *Mosaic5gList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mosaic5g, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mosaic5gList.
func (in *Mosaic5gList) DeepCopy() *Mosaic5gList {
	if in == nil {
		return nil
	}
	out := new(Mosaic5gList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mosaic5gList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mosaic5gSpec) DeepCopyInto(out *Mosaic5gSpec) {
	*out = *in
	out.Snap = in.Snap
	out.NodeFunction = in.NodeFunction
	out.MmeIpAddr = in.MmeIpAddr
	out.EutraBand = in.EutraBand
	out.DownlinkFrequency = in.DownlinkFrequency
	out.UplinkFrequencyOffset = in.UplinkFrequencyOffset
	out.NumberRbDl = in.NumberRbDl
	out.NbAntennasTx = in.NbAntennasTx
	out.NbAntennasRx = in.NbAntennasRx
	out.TxGain = in.TxGain
	out.RxGain = in.RxGain
	out.EnbName = in.EnbName
	out.EnbId = in.EnbId
	out.ParallelConfig = in.ParallelConfig
	out.MaxRxGain = in.MaxRxGain
	out.CuPortc = in.CuPortc
	out.DuPortc = in.DuPortc
	out.CuPortd = in.CuPortd
	out.DuPortd = in.DuPortd
	out.RruPortc = in.RruPortc
	out.RruPortd = in.RruPortd
	out.RccPortc = in.RccPortc
	out.RccPortd = in.RccPortd
	out.RccRruTrPreference = in.RccRruTrPreference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mosaic5gSpec.
func (in *Mosaic5gSpec) DeepCopy() *Mosaic5gSpec {
	if in == nil {
		return nil
	}
	out := new(Mosaic5gSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mosaic5gStatus) DeepCopyInto(out *Mosaic5gStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mosaic5gStatus.
func (in *Mosaic5gStatus) DeepCopy() *Mosaic5gStatus {
	if in == nil {
		return nil
	}
	out := new(Mosaic5gStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapDescription) DeepCopyInto(out *SnapDescription) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapDescription.
func (in *SnapDescription) DeepCopy() *SnapDescription {
	if in == nil {
		return nil
	}
	out := new(SnapDescription)
	in.DeepCopyInto(out)
	return out
}
